services:
  mysql:
    image: mariadb:10
    container_name: mysql.chatapp.internal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-chatpasswordsecret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-chat_app}
      MYSQL_USER: ${MYSQL_USER:-chatuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-chatpasswordstrongerthanstrongbutnottoostrong}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - chat-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend.chatapp.internal
    environment:
      - MYSQL_USER=${MYSQL_USER:-chatuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-chatpasswordstrongerthanstrongbutnottoostrong}
      - MYSQL_HOST=${MYSQL_HOST:-mysql.chatapp.internal}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-chat_app}
      - JWT_SECRET=${JWT_SECRET:-chatpasswordstrongerthanstrongbutnottoostrong}
      - ENV=${ENV:-production}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - chat-network

  frontend:
    build: ./frontend
    container_name: frontend.chatapp.internal
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend.chatapp.internal
    networks:
      - chat-network


volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind

networks:
  chat-network:
    driver: bridge
