services:
  mysql:
    image: mariadb:10
    container_name: mysql.chatapp.internal
    environment:
      MYSQL_ROOT_PASSWORD: chatpasswordsecret
      MYSQL_DATABASE: chat_app
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpasswordstrongerthanstrongbutnottoostrong
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - chat-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -pchatpasswordsecret"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend.chatapp.internal
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpasswordstrongerthanstrongbutnottoostrong
      MYSQL_HOST: mysql.chatapp.internal
      MYSQL_PORT: 3306
      MYSQL_DATABASE: chat_app
      JWT_SECRET: chatpasswordstrongerthanstrongbutnottoostrong
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - chat-network

  frontend:
    build: ./frontend
    container_name: frontend.chatapp.internal
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:8080
    networks:
      - chat-network

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind

networks:
  chat-network:
    driver: bridge
