version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080
    networks:
      - chat-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - chat-network

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: chat-app
    ports:
      - "3306:3306"
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
